version: '3.7'

services:
  ls01:
    image: logstash:${VERSION}
    restart: unless-stopped
    container_name: ls01
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    volumes:
      - ./data/pipeline/:/usr/share/logstash/pipeline/
      - ./data/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - elastic
        #expose:
        # - 5044
    ports:
      - "9600:9600"
      - "5400:5400"
      - "5400:5400/udp"
      - "12201:12201/udp"
      - "12201:12201/tcp"
      - "12202:12202"
networks:
  elastic:
    driver: bridge
